### ISSUE TITLE
Muncoordinated doesn't operate properly if someone else is viewing the link

### ISSUE THREAD

**Issue by MPham95** [MaxwellBo/Muncoordinated-2#8] opened 2018-03-30 04:30 UTC
As a Director, I can operate the software normally as long as no one else is viewing the link to the committee whilst if someone else is viewing it on their own device, to view changes I must refresh the page.

**Comment by MaxwellBo** [comment] 2018-03-30 05:26
I have a suspicion that this was caused by the introduction of the new motions tab

**Comment by MaxwellBo** [comment] 2018-03-30 06:27
Closed by 5aa5997

**Closed by MaxwellBo** 2018-03-30 06:27 UTC
Labels: bug
